SYMBOLS = ["BTCUSD"]
ENTRY_TIMEFRAME = "M5"
CONFIRM_TIMEFRAME = "M5"
TREND_TIMEFRAME = "M5"

TRADE_SESSION_START = 0
TRADE_SESSION_END = 24

BUY_THRESHOLD = 0.20
SELL_THRESHOLD = -0.20
SENTIMENT_OVERRIDE_THRESH = 0.60
REQUIRE_ML_PA_CONFLUENCE = False
ML_CONFIDENCE_GATE = 0.0

W_PA, W_ML, W_SENT = 0.70, 0.15, 0.15
MAX_DAILY_TRADES = 999
MAX_DAILY_LOSS_PCT = 0.05

MIN_LOT = 0.01
MAX_LOT = 10.0
MAX_OPEN_POSITIONS = 3
MAX_DRAWDOWN_PCT = 0.10
NEWS_BLACKOUT_MINUTES = 5

USE_SIMULATOR = True

ZERO_DECIMAL = {"JPY", "KRW", "TWD", "INR", "IDR", "VND"}
TWO_DECIMAL = {"BTCUSD", "ETHUSD", "XRPUSD"}

CONTRACT_SIZE = {
    "BTCUSD": 1,
    "ETHUSD": 1,
    "XRPUSD": 1,
}

def pip_size(symbol: str) -> float:
    if symbol in TWO_DECIMAL:
        return 0.01
    return 0.01 if any(symbol.endswith(c) for c in ZERO_DECIMAL) else 0.0001

def contract_size(symbol: str) -> int:
    return CONTRACT_SIZE.get(symbol, 100_000)

ATR_MULT = {
    "BTCUSD": {"sl": 1.0, "tp": 2.5},
    "EURUSD": {"sl": 1.0, "tp": 2.5},
    "USDILS": {"sl": 1.0, "tp": 2.5},
    "USDZAR": {"sl": 1.0, "tp": 2.5},
}

LSTM_SEQ_LEN = 30
XGB_N_ESTIMATORS = 100
ML_LOOKAHEAD_BARS = 2
ML_LABEL_THRESHOLD = 0.0008

LOOP_INTERVAL_SECONDS = 300
SENTIMENT_REFRESH_MINUTES = 15

MAGIC_NUMBER = 20260601
MAX_SPREAD = {
    "BTCUSD": 5.0,
    "EURUSD": 1.5,
    "USDILS": 5.0,
    "USDZAR": 8.0,
}

BASE_RISK_PCT = {"BTCUSD": 0.005, "EURUSD": 1.5, "USDILS": 0.003, "USDZAR": 0.003}
MAX_RISK_PCT = {"BTCUSD": 0.01, "EURUSD": 1.5, "USDILS": 0.008, "USDZAR": 0.008}

INITIAL_BALANCE = 100.0
RISK_SCALE_FACTOR = 0.5

HC_PA_SCORE_THRESHOLD = 0.40
HC_ML_PROB_BUY = 0.70
HC_ML_PROB_SELL = 0.30
HC_SL_ATR_MULT = 0.8
HC_TP_ATR_MULT_DEFAULT = 1.5
HC_TP_ATR_MULT_NEAR_SR = 2.0
MAX_RISK_MULTIPLIER = 1.5
MAX_RISK_PCT_PER_TRADE = 0.10

RAPID_SL_MULT = 0.5
RAPID_TP_MULT = {"BTCUSD": 1.0, "EURUSD": 1.5, "GBPUSD": 2.0, "AUDUSD": 1.5, "USDCAD": 2.0, "NZDUSD": 2.0, "USDILS": 2.0, "USDZAR": 2.0}
RAPID_PA_THRESHOLD = 0.5
RAPID_BE_ATR_MULT = 0

LEVERAGE = 5
SPREAD_PIPS = 1.0
SLIPPAGE_PIPS = 0.0
DB_PATH = "logs/trades.db"
MODELS_DIR = "models"
